#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_MAIN                                100
#define IDI_ICON1                               101
#define IDR_MENU1                               102
#define DLG_SETTINGS                            103
#define DLG_NAMEGEN                             104
#define DLG_PACKRELEASE                         106
#define DLG_NFOVIEWER                           108
#define IDC_BTN_OK                              1000
#define IDC_EDT_PROGRAM                         1000
#define IDC_EDT_DATECHECK                       1001
#define IDC_EDT_PROTECTION                      1001
#define IDC_BTN_GENERATE                        1002
#define IDC_BUTTON1                             1002
#define IDC_EDT_WEBSITE                         1002
#define IDC_LIST_FILES                          1002
#define IDC_EDIT1                               1003
#define IDC_EDT_RELEASENAME                     1003
#define IDC_EDT_RLZSIZE                         1003
#define IDC_EDT_SETTINGS_CRACKER                1003
#define IDC_BTN_REMOVE                          1004
#define IDC_EDT_RLZDATE                         1004
#define IDC_EDT_RLZTYPE                         1005
#define IDC_EDT_SETTINGS_PLATFORM               1005
#define IDC_BTN_PACK                            1006
#define IDC_EDT_COMPANY                         1006
#define IDC_EDT_CRACKER                         1007
#define IDC_CHK_ONTOP                           1008
#define IDC_EDT_PLATFORM                        1008
#define IDC_EDT_INSTALLNOTES                    1009
#define IDC_EDT_NAME_RELEASENAME                1010
#define IDC_EDT_RELEASENOTES                    1010
#define IDC_BTN_FORMATRELEASE                   1011
#define IDC_EDT_NAME_RELEASETYPE                1011
#define IDC_BTN_PREVIEW                         1012
#define IDC_EDT_NAME_COMPANY                    1012
#define IDC_BTN_FORMATINSTALL                   1013
#define IDC_EDT_NAME_PROGRAM                    1013
#define IDC_STC_CLICKME1                        1014
#define IDC_BTN_PACKRELEASE                     1015
#define IDC_STATIC1                             1016
#define IDC_STATIC2                             1017
#define IDC_STATIC3                             1018
#define IDC_STATIC4                             1019
#define IDC_STATIC5                             1020
#define IDC_STATIC6                             1021
#define IDC_STATIC7                             1022
#define IDC_STATIC8                             1023
#define IDM_HELP_ABOUT                          40000
#define IDM_FILE_EXIT                           40001
#define IDM_FILE_SAVE                           40002
#define IDM_TOOLS_SETTINGS                      40003
#define IDM_TOOLS_PREVIEW                       40004
#define IDC_STC_CLICKME2                        40005
#define IDM_TOOLS_NAMEGEN                       40005
